name: Build and push Docker image

on:
  push:
    branches:
      - main  # Sostituisci con il nome del tuo branch principale

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.NAME }}  # Il tuo nome utente Docker Hub
          password: ${{ secrets.PASSWORD }}  # La tua password Docker Hub

      - name: Build the Docker image
        uses: docker/build-push-action@v3
        with:
          context: .  # Il contesto di build, in questo caso l'intera repository
          push: true  # Pubblica l'immagine su Docker Hub
          tags: ${{ secrets.GITHUB_USERNAME }}/ti-voglio-bene-denver:latest  # Nome e tag dell'immagine
